modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://discord.gg/TPjjuHFfZV"
[[mods]]
modId="gmm"
version="2.3"
displayName="MineTopia Mod"
updateJSONURL="https://raw.githubusercontent.com/GhostgamesDHG/update.json/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minetopia-extra-mod"
logoFile="pack.png"
authors="ArmedEndmion"

description='''
         This mod adds realism to the game!
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"