package com.armedendmion.minetopiamod.init;

import com.armedendmion.minetopiamod.MineTopiaMod;
import com.armedendmion.minetopiamod.items.MoneyTooltip;
import net.minecraft.world.item.*;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {
public static final DeferredRegister<Item> ITEMS =
        DeferredRegister.create(ForgeRegistries.ITEMS, MineTopiaMod.MOD_ID);

    public static final RegistryObject<Item> IPHONE_7_BLACK = ModTabs.addToItemsTab(ITEMS.register("iphone_7_black", () -> new Item(new Item.Properties().stacksTo(1))));
    public static final RegistryObject<Item> IPHONE_7_PINK = ModTabs.addToItemsTab(ITEMS.register("iphone_7_pink", () -> new Item(new Item.Properties().stacksTo(1))));
    public static final RegistryObject<Item> IPHONE_7_YELLOW = ModTabs.addToItemsTab(ITEMS.register("iphone_7_yellow", () -> new Item(new Item.Properties().stacksTo(1))));
    public static final RegistryObject<Item> IPHONE_7_GREEN = ModTabs.addToItemsTab(ITEMS.register("iphone_7_green", () -> new Item(new Item.Properties().stacksTo(1))));
    public static final RegistryObject<Item> IPHONE_7_BLUE = ModTabs.addToItemsTab(ITEMS.register("iphone_7_blue", () -> new Item(new Item.Properties().stacksTo(1))));
    public static final RegistryObject<Item> IPHONE_7_RED = ModTabs.addToItemsTab(ITEMS.register("iphone_7_red", () -> new Item(new Item.Properties().stacksTo(1))));

    //MONEY
    public static final RegistryObject<Item> MONEY1 = ModTabs.addToItemsTab(ITEMS.register("0.10euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY2 = ModTabs.addToItemsTab(ITEMS.register("1euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY3 = ModTabs.addToItemsTab(ITEMS.register("5euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY4 = ModTabs.addToItemsTab(ITEMS.register("10euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY5 = ModTabs.addToItemsTab(ITEMS.register("20euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY6 = ModTabs.addToItemsTab(ITEMS.register("50euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY7 = ModTabs.addToItemsTab(ITEMS.register("100euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY8 = ModTabs.addToItemsTab(ITEMS.register("200euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY9 = ModTabs.addToItemsTab(ITEMS.register("500euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> MONEY10 = ModTabs.addToItemsTab(ITEMS.register("1000euro", () -> new MoneyTooltip(new Item.Properties())));
    public static final RegistryObject<Item> DEBIT_CARD = ModTabs.addToItemsTab(ITEMS.register("debit_card", () -> new Item(new Item.Properties())));

    //CASINO COINS
    public static final RegistryObject<Item> CASINO_COIN_BLUE = ModTabs.addToItemsTab(ITEMS.register("casino_coin_blue", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CASINO_COIN_GOLD = ModTabs.addToItemsTab(ITEMS.register("casino_coin_gold", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CASINO_COIN_GREEN = ModTabs.addToItemsTab(ITEMS.register("casino_coin_green", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CASINO_COIN_ORANGE = ModTabs.addToItemsTab(ITEMS.register("casino_coin_orange", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CASINO_COIN_RED = ModTabs.addToItemsTab(ITEMS.register("casino_coin_red", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CASINO_COIN_SILVER = ModTabs.addToItemsTab(ITEMS.register("casino_coin_silver", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WHEELCOIN = ModTabs.addToItemsTab(ITEMS.register("wheelcoin", () -> new Item(new Item.Properties())));

    //ALL THE OTHER ITEMS
    public static final RegistryObject<Item> BLUE_CRYSTAL = ModTabs.addToItemsTab(ITEMS.register("blue_crystal", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PINK_BALLOON = ModTabs.addToItemsTab(ITEMS.register("pink_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RED_BALLOON = ModTabs.addToItemsTab(ITEMS.register("red_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_BALLOON = ModTabs.addToItemsTab(ITEMS.register("orange_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> GREEN_BALLOON = ModTabs.addToItemsTab(ITEMS.register("green_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_BALLOON = ModTabs.addToItemsTab(ITEMS.register("yellow_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BLUE_BALLOON = ModTabs.addToItemsTab(ITEMS.register("blue_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> SPORTS_WATCH = ModTabs.addToItemsTab(ITEMS.register("sports_watch", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RING = ModTabs.addToItemsTab(ITEMS.register("ring", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BLUE_WHITE_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("blue_white_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RAINBOW_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("rainbow_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RED_WHITE_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("red_white_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MINETOPIABAG = ModTabs.addToItemsTab(ITEMS.register("minetopiabag", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PEPPERSPRAY = ModTabs.addToItemsTab(ITEMS.register("pepperspray", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WATCH = ModTabs.addToItemsTab(ITEMS.register("watch", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRONZE_PRISONCOIN = ModTabs.addToItemsTab(ITEMS.register("bronze_prisoncoin", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> SILVER_PRISONCOIN = ModTabs.addToItemsTab(ITEMS.register("silver_prisoncoin", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> LEGEND_50 = ModTabs.addToItemsTab(ITEMS.register("legend_50", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> LEGEND_1 = ModTabs.addToItemsTab(ITEMS.register("legend_1", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> EPIC_10 = ModTabs.addToItemsTab(ITEMS.register("epic_10", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> EPIC_5 = ModTabs.addToItemsTab(ITEMS.register("epic_5", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> EPIC_1 = ModTabs.addToItemsTab(ITEMS.register("epic_1", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> COMMON_50 = ModTabs.addToItemsTab(ITEMS.register("common_50", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> COMMON_10 = ModTabs.addToItemsTab(ITEMS.register("common_10", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> COMMON_1 = ModTabs.addToItemsTab(ITEMS.register("common_1", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MODERN_WALKING_STICK = ModTabs.addToItemsTab(ITEMS.register("modern_walking_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MAGICWAND = ModTabs.addToItemsTab(ITEMS.register("magicwand", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MAGICWAND_BLUE = ModTabs.addToItemsTab(ITEMS.register("magicwand_blue", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MAGICWAND_GREEN = ModTabs.addToItemsTab(ITEMS.register("magicwand_green", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MAGICWAND_RED = ModTabs.addToItemsTab(ITEMS.register("magicwand_red", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MAGICWAND_YELLOW = ModTabs.addToItemsTab(ITEMS.register("magicwand_yellow", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN1 = ModTabs.addToItemsTab(ITEMS.register("racecoin1", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN10 = ModTabs.addToItemsTab(ITEMS.register("racecoin10", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN50 = ModTabs.addToItemsTab(ITEMS.register("racecoin50", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN100 = ModTabs.addToItemsTab(ITEMS.register("racecoin100", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN500 = ModTabs.addToItemsTab(ITEMS.register("racecoin500", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN1000 = ModTabs.addToItemsTab(ITEMS.register("racecoin1000", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN2500 = ModTabs.addToItemsTab(ITEMS.register("racecoin2500", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RACECOIN5000 = ModTabs.addToItemsTab(ITEMS.register("racecoin5000", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> ROLEX_GOLD = ModTabs.addToItemsTab(ITEMS.register("rolex_gold", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> ROLEX_DIAMOND = ModTabs.addToItemsTab(ITEMS.register("rolex_diamond", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> ROLEX_SILVER = ModTabs.addToItemsTab(ITEMS.register("rolex_silver", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PCB_DUST = ModTabs.addToItemsTab(ITEMS.register("pcb_dust", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PCB = ModTabs.addToItemsTab(ITEMS.register("pcb", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> STEEL_INGOT = ModTabs.addToItemsTab(ITEMS.register("steel_ingot", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> APPLE_WATCH = ModTabs.addToItemsTab(ITEMS.register("apple_watch", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> AIRPODS = ModTabs.addToItemsTab(ITEMS.register("airpods", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRACELET = ModTabs.addToItemsTab(ITEMS.register("bracelet", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRACELET2 = ModTabs.addToItemsTab(ITEMS.register("bracelet2", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> TABLET = ModTabs.addToItemsTab(ITEMS.register("tablet", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_BRONZE = ModTabs.addToItemsTab(ITEMS.register("key_dice_bronze", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_DIAMOND = ModTabs.addToItemsTab(ITEMS.register("key_dice_diamond", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_EMERALD = ModTabs.addToItemsTab(ITEMS.register("key_dice_emerald", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_GOLD = ModTabs.addToItemsTab(ITEMS.register("key_dice_gold", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_MYSTIC = ModTabs.addToItemsTab(ITEMS.register("key_dice_mystic", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_REDSTONE = ModTabs.addToItemsTab(ITEMS.register("key_dice_redstone", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_DICE_SILVER = ModTabs.addToItemsTab(ITEMS.register("key_dice_silver", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_BRONZE = ModTabs.addToItemsTab(ITEMS.register("key_hammer_bronze", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_DIAMOND = ModTabs.addToItemsTab(ITEMS.register("key_hammer_diamond", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_EMERALD = ModTabs.addToItemsTab(ITEMS.register("key_hammer_emerald", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_GOLD = ModTabs.addToItemsTab(ITEMS.register("key_hammer_gold", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_MYSTIC = ModTabs.addToItemsTab(ITEMS.register("key_hammer_mystic", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_REDSTONE = ModTabs.addToItemsTab(ITEMS.register("key_hammer_redstone", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> KEY_HAMMER_SILVER = ModTabs.addToItemsTab(ITEMS.register("key_hammer_silver", () -> new Item(new Item.Properties())));

//NEED RECIPE
    public static final RegistryObject<Item> POCKET_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("pocket_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CHRISTMAS_BALLOON = ModTabs.addToItemsTab(ITEMS.register("christmas_balloon", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> HINKING_BRANCH = ModTabs.addToItemsTab(ITEMS.register("hinking_branch", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BLACK_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("black_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BLUE_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("blue_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CYAN_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("cyan_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> LIME_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("lime_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> GREEN_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("green_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("purple_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> RED_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("red_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WHITE_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("white_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_UMBRELLA = ModTabs.addToItemsTab(ITEMS.register("yellow_umbrella", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BLACK_FLY_SWATTER = ModTabs.addToItemsTab(ITEMS.register("black_fly_swatter", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> GOLDEN_FLY_SWATTER = ModTabs.addToItemsTab(ITEMS.register("golden_fly_swatter", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> EASTER_BASKET = ModTabs.addToItemsTab(ITEMS.register("easter_basket", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> GUITAR = ModTabs.addToItemsTab(ModTabs.addToItemsTab(ITEMS.register("guitar", () -> new Item(new Item.Properties()))));
    public static final RegistryObject<Item> SANTA_CLAUS_STAFF = ModTabs.addToItemsTab(ITEMS.register("santa_claus_staff", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> PUMPKINLANTERN = ModTabs.addToItemsTab(ITEMS.register("pumpkinlantern", () -> new Item(new Item.Properties())));

    //FOOD
    public static final RegistryObject<Item> BANANA = ModTabs.addToFoodTab(ModTabs.addToFoodTab(ITEMS.register("banana", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER)))));
    public static final RegistryObject<Item> STRAWBERRY = ModTabs.addToFoodTab(ModTabs.addToFoodTab(ITEMS.register("strawberry", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER)))));
    public static final RegistryObject<Item> HAMBURGER = ModTabs.addToFoodTab(ITEMS.register("hamburger", () -> new Item(new Item.Properties().food(ModFood.TENHUNGER))));
    public static final RegistryObject<Item> SANDWICH = ModTabs.addToFoodTab(ITEMS.register("sandwich", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> PINEAPPLE = ModTabs.addToFoodTab(ITEMS.register("pineapple", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> BACON = ModTabs.addToFoodTab(ITEMS.register("bacon", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> COOKED_BACON = ModTabs.addToFoodTab(ITEMS.register("cooked_bacon", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> CHICKEN = ModTabs.addToFoodTab(ITEMS.register("chicken", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> COOKED_CHICKEN = ModTabs.addToFoodTab(ITEMS.register("cooked_chicken", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> HOTDOG = ModTabs.addToFoodTab(ITEMS.register("hotdog", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> ICECREAM = ModTabs.addToFoodTab(ITEMS.register("icecream", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CODFISH = ModTabs.addToFoodTab(ITEMS.register("codfish", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> FRIES = ModTabs.addToFoodTab(ITEMS.register("fries", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> PIZZA = ModTabs.addToFoodTab(ITEMS.register("pizza", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CHICKEN_BUCKET = ModTabs.addToFoodTab(ITEMS.register("chicken_bucket", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> FRUIT_SKEWER = ModTabs.addToFoodTab(ITEMS.register("fruit_skewer", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> SUSHI = ModTabs.addToFoodTab(ITEMS.register("sushi", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> SUSHI_PACKAGE = ModTabs.addToFoodTab(ITEMS.register("sushi_package", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> MUFFIN = ModTabs.addToFoodTab(ITEMS.register("muffin", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> VANILLA_MUFFIN = ModTabs.addToFoodTab(ITEMS.register("vanilla_muffin", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_MUFFIN = ModTabs.addToFoodTab(ITEMS.register("chocolate_muffin", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> JELLYBEANS = ModTabs.addToFoodTab(ITEMS.register("jellybeans", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CANDY_CANE = ModTabs.addToFoodTab(ITEMS.register("candy_cane", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> DOUBLE_SUSHI_PACKAGE = ModTabs.addToFoodTab(ITEMS.register("double_sushi_package", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> CUPCAKES = ModTabs.addToFoodTab(ITEMS.register("cupcakes", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CHEESE = ModTabs.addToFoodTab(ITEMS.register("cheese", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> GRAPES = ModTabs.addToFoodTab(ITEMS.register("grapes", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> RED_GRAPES = ModTabs.addToFoodTab(ITEMS.register("red_grapes", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> HOP = ModTabs.addToFoodTab(ITEMS.register("hop", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CHIPS_NATURAL = ModTabs.addToFoodTab(ITEMS.register("chips_natural", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> DONUT_BLUEBERRIES = ModTabs.addToFoodTab(ITEMS.register("donut_blueberries", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONUT_CHOCOLATE = ModTabs.addToFoodTab(ITEMS.register("donut_chocolate", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONUT_HALLOWEEN = ModTabs.addToFoodTab(ITEMS.register("donut_halloween", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONUT_STRAWBERRY = ModTabs.addToFoodTab(ITEMS.register("donut_strawberry", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONUT_CHRISTMAS = ModTabs.addToFoodTab(ITEMS.register("donut_christmas", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONUT_WHITE = ModTabs.addToFoodTab(ITEMS.register("donut_white", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> STRAWBERRY_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("strawberry_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_LETTER = ModTabs.addToFoodTab(ITEMS.register("chocolate_letter", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_BAR = ModTabs.addToFoodTab(ITEMS.register("chocolate_bar", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> APFELSTRUDEL = ModTabs.addToFoodTab(ITEMS.register("apfelstrudel", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> BITTERBALLEN = ModTabs.addToFoodTab(ITEMS.register("bitterballen", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CORN = ModTabs.addToFoodTab(ITEMS.register("corn", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> LETTUCE = ModTabs.addToFoodTab(ITEMS.register("lettuce", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> PAPRIKA = ModTabs.addToFoodTab(ITEMS.register("paprika", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> PEPPER = ModTabs.addToFoodTab(ITEMS.register("pepper", () -> new Item(new Item.Properties().food(ModFood.PEPPER))));
    public static final RegistryObject<Item> TOMATO = ModTabs.addToFoodTab(ITEMS.register("tomato", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> WHITE_GRAPES = ModTabs.addToFoodTab(ITEMS.register("white_grapes", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> WEED = ModTabs.addToFoodTab(ITEMS.register("weed", () -> new Item(new Item.Properties().food(ModFood.WEED))));
    public static final RegistryObject<Item> PURPLE_WEED = ModTabs.addToFoodTab(ITEMS.register("purple_weed", () -> new Item(new Item.Properties().food(ModFood.PURPLE_WEED))));
    public static final RegistryObject<Item> DRAGONFLESH = ModTabs.addToFoodTab(ITEMS.register("dragonflesh", () -> new Item(new Item.Properties().food(ModFood.DRAGONFLESH))));
    public static final RegistryObject<Item> UNICORNFLESH = ModTabs.addToFoodTab(ITEMS.register("unicornflesh", () -> new Item(new Item.Properties().food(ModFood.UNICORNFLESH))));
    public static final RegistryObject<Item> COCAINE = ModTabs.addToFoodTab(ITEMS.register("cocaine", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> CAN_LENTILES_SOUP = ModTabs.addToFoodTab(ITEMS.register("can_lentiles_soup", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> PEPPERNUT = ModTabs.addToFoodTab(ITEMS.register("peppernut", () -> new Item(new Item.Properties().food(ModFood.ONEHUNGER))));
    public static final RegistryObject<Item> CHOCOLATES = ModTabs.addToFoodTab(ITEMS.register("chocolates", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> FRIES_MAYONNAISE = ModTabs.addToFoodTab(ITEMS.register("fries_mayonnaise", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("chocolate_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> KIDS_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("kids_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_KIDS_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("chocolate_kids_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> DEEP_FRIED_RAISIN_BUN = ModTabs.addToFoodTab(ITEMS.register("deep_fried_raisin_bun", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> SMURFS_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("smurfs_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> VANILLA_ICECREAM = ModTabs.addToFoodTab(ITEMS.register("vanilla_icecream", () -> new Item(new Item.Properties().food(ModFood.THREEHUNGER))));
    public static final RegistryObject<Item> FLEMISH_FRIES = ModTabs.addToFoodTab(ITEMS.register("flemish_fries", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> AVOCADO = ModTabs.addToFoodTab(ITEMS.register("avocado", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> BROWNIE = ModTabs.addToFoodTab(ITEMS.register("brownie", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> DONER_SANDWICH = ModTabs.addToFoodTab(ITEMS.register("doner_sandwich", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> HEALTHY_SANDWICH = ModTabs.addToFoodTab(ITEMS.register("healthy_sandwich", () -> new Item(new Item.Properties().food(ModFood.BROODJE_GEZOND))));
    public static final RegistryObject<Item> SAUSAGE_ROLL = ModTabs.addToFoodTab(ITEMS.register("sausage_roll", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> WIENER_SCHNITZEL = ModTabs.addToFoodTab(ITEMS.register("wiener_schnitzel", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> CROISSANT = ModTabs.addToFoodTab(ITEMS.register("croissant", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> DATES = ModTabs.addToFoodTab(ITEMS.register("dates", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> HERRING = ModTabs.addToFoodTab(ITEMS.register("herring", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CHEESE_FONDUE = ModTabs.addToFoodTab(ITEMS.register("cheese_fondue", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CARP = ModTabs.addToFoodTab(ITEMS.register("carp", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CHRISTMAS_COOKIE = ModTabs.addToFoodTab(ITEMS.register("christmas_cookie", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CHICKEN_NUGGETS = ModTabs.addToFoodTab(ITEMS.register("chicken_nuggets", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> LOBSTER = ModTabs.addToFoodTab(ITEMS.register("lobster", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> RED_LOLLYPOP = ModTabs.addToFoodTab(ITEMS.register("red_lollypop", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> LOLLYPOP = ModTabs.addToFoodTab(ITEMS.register("lollypop", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> LIEGE_WAFFLE = ModTabs.addToFoodTab(ITEMS.register("liege_waffle", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> MUSSELS = ModTabs.addToFoodTab(ITEMS.register("mussels", () -> new Item(new Item.Properties().food(ModFood.FIVEHUNGER))));
    public static final RegistryObject<Item> OYSTER = ModTabs.addToFoodTab(ITEMS.register("oyster", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> OYSTERS = ModTabs.addToFoodTab(ITEMS.register("oysters", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> DEEP_FRIED_DOUGHNUT_BALLS = ModTabs.addToFoodTab(ITEMS.register("deep_fried_doughnut_balls", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> PRETZEL = ModTabs.addToFoodTab(ITEMS.register("pretzel", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> REDFISH = ModTabs.addToFoodTab(ITEMS.register("redfish", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> PIKE = ModTabs.addToFoodTab(ITEMS.register("pike", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> SPARERIBS = ModTabs.addToFoodTab(ITEMS.register("spareribs", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> COOKED_SPARERIBS = ModTabs.addToFoodTab(ITEMS.register("cooked_spareribs", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> STURGEON = ModTabs.addToFoodTab(ITEMS.register("sturgeon", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> STROOPWAFEL = ModTabs.addToFoodTab(ITEMS.register("stroopwafel", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> TURKISH_PIZZA = ModTabs.addToFoodTab(ITEMS.register("turkish_pizza", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> WAFFLE = ModTabs.addToFoodTab(ITEMS.register("waffle", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> SALTY_FISH = ModTabs.addToFoodTab(ITEMS.register("salty_fish", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> FRIED_FISH = ModTabs.addToFoodTab(ITEMS.register("fried_fish", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> OMELET = ModTabs.addToFoodTab(ITEMS.register("omelet", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> MEATBALLS = ModTabs.addToFoodTab(ITEMS.register("meatballs", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> LASAGNE = ModTabs.addToFoodTab(ITEMS.register("lasagne", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> POPCORN = ModTabs.addToFoodTab(ITEMS.register("popcorn", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> SPAGHETTI = ModTabs.addToFoodTab(ITEMS.register("spaghetti", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> WRAP = ModTabs.addToFoodTab(ITEMS.register("wrap", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_EGG = ModTabs.addToFoodTab(ITEMS.register("chocolate_egg", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> LEMON = ModTabs.addToFoodTab(ITEMS.register("lemon", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> KIWI = ModTabs.addToFoodTab(ITEMS.register("kiwi", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> FRIKANDELBROODJE = ModTabs.addToFoodTab(ITEMS.register("frikandelbroodje", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> DROP = ModTabs.addToFoodTab(ITEMS.register("drop", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> CANDY_GREEN = ModTabs.addToFoodTab(ITEMS.register("candy_green", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> CANDY_PURPLE = ModTabs.addToFoodTab(ITEMS.register("candy_purple", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> CANDY_RED = ModTabs.addToFoodTab(ITEMS.register("candy_red", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> FORTUNE_COOKIE = ModTabs.addToFoodTab(ITEMS.register("fortune_cookie", () -> new Item(new Item.Properties().food(ModFood.GELUKSKOEKJE))));
    public static final RegistryObject<Item> ORANGE = ModTabs.addToFoodTab(ITEMS.register("orange", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> RASPBERRY = ModTabs.addToFoodTab(ITEMS.register("raspberry", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> PEAR = ModTabs.addToFoodTab(ITEMS.register("pear", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> TOMATO_SOUP = ModTabs.addToFoodTab(ITEMS.register("tomato_soup", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> ROOKWORST = ModTabs.addToFoodTab(ITEMS.register("rookworst", () -> new Item(new Item.Properties().food(ModFood.SEVENHUNGER))));
    public static final RegistryObject<Item> CHEESECAKE = ModTabs.addToFoodTab(ITEMS.register("cheesecake", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> BOSSCHE_BOL = ModTabs.addToFoodTab(ITEMS.register("bossche_bol", () -> new Item(new Item.Properties().food(ModFood.FOURHUNGER))));
    public static final RegistryObject<Item> CHOCOLATE_CAKE = ModTabs.addToFoodTab(ITEMS.register("chocolate_cake", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> VANILLA_CAKE = ModTabs.addToFoodTab(ITEMS.register("vanilla_cake", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> SHRIMP = ModTabs.addToFoodTab(ITEMS.register("shrimp", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> COOKED_SHRIMP = ModTabs.addToFoodTab(ITEMS.register("cooked_shrimp", () -> new Item(new Item.Properties().food(ModFood.EIGHTHUNGER))));
    public static final RegistryObject<Item> MERINGUE = ModTabs.addToFoodTab(ITEMS.register("meringue", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> TAAITAAI = ModTabs.addToFoodTab(ITEMS.register("taaitaai", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> SPICED_BESQUIT = ModTabs.addToFoodTab(ITEMS.register("spiced_besquit", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> TOMPOUCE = ModTabs.addToFoodTab(ITEMS.register("tompouce", () -> new Item(new Item.Properties().food(ModFood.TWOHUNGER))));
    public static final RegistryObject<Item> COOKED_CORN = ModTabs.addToFoodTab(ITEMS.register("cooked_corn", () -> new Item(new Item.Properties().food(ModFood.SIXHUNGER))));
    public static final RegistryObject<Item> FLOUR = ModTabs.addToFoodTab(ITEMS.register("flour", () -> new Item(new Item.Properties())));
//POTIONS
    public static final RegistryObject<Item> WATER_BOTTLE = ModTabs.addToFoodTab(ITEMS.register("water_bottle", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> COFFEE = ModTabs.addToFoodTab(ITEMS.register("coffee", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> BEER_BOTTLE = ModTabs.addToFoodTab(ITEMS.register("beer_bottle", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> BEER_GLASS = ModTabs.addToFoodTab(ITEMS.register("beer_glass", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> MILKSHAKE = ModTabs.addToFoodTab(ITEMS.register("milkshake", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> ALCOHOL_BOTTLE = ModTabs.addToFoodTab(ITEMS.register("alcohol_bottle", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> ORANGE_JUICE = ModTabs.addToFoodTab(ITEMS.register("orange_juice", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
//VITAMINES
    public static final RegistryObject<Item> VITAMINE_A = ModTabs.addToFoodTab(ITEMS.register("vitamine_a", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> VITAMINE_B = ModTabs.addToFoodTab(ITEMS.register("vitamine_b", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> VITAMINE_C = ModTabs.addToFoodTab(ITEMS.register("vitamine_c", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> VITAMINE_D = ModTabs.addToFoodTab(ITEMS.register("vitamine_d", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> VITAMINE_E = ModTabs.addToFoodTab(ITEMS.register("vitamine_e", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> VITAMINE_F = ModTabs.addToFoodTab(ITEMS.register("vitamine_f", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    //ANIMAL FOOD
    public static final RegistryObject<Item> DOG_FOOD = ModTabs.addToFoodTab(ITEMS.register("dog_food", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));
    public static final RegistryObject<Item> CAT_FOOD = ModTabs.addToFoodTab(ITEMS.register("cat_food", () -> new Item(new Item.Properties().food(ModFood.COCAINE))));

    //HATS
    public static final RegistryObject<Item> DEMON_RED_HORNS = ITEMS.register("demon_red_horns", () -> new Item(new Item.Properties()));

    //SEEDS
    public static final RegistryObject<Item> CORN_SEEDS = ModTabs.addToFoodTab(ITEMS.register("corn_seeds", () -> new ItemNameBlockItem(ModBlocks.CORN_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> GRAPES_SEEDS = ModTabs.addToFoodTab(ITEMS.register("grapes_seeds", () -> new ItemNameBlockItem(ModBlocks.GRAPES_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> WHITE_GRAPES_SEEDS = ModTabs.addToFoodTab(ITEMS.register("white_grapes_seeds", () -> new ItemNameBlockItem(ModBlocks.WHITE_GRAPES_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> RED_GRAPES_SEEDS = ModTabs.addToFoodTab(ITEMS.register("red_grapes_seeds", () -> new ItemNameBlockItem(ModBlocks.RED_GRAPES_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> HOP_SEEDS = ModTabs.addToFoodTab(ITEMS.register("hop_seeds", () -> new ItemNameBlockItem(ModBlocks.HOP_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> LETTUCE_SEEDS = ModTabs.addToFoodTab(ITEMS.register("lettuce_seeds", () -> new ItemNameBlockItem(ModBlocks.LETTUCE_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> PAPRIKA_SEEDS = ModTabs.addToFoodTab(ITEMS.register("paprika_seeds", () -> new ItemNameBlockItem(ModBlocks.PAPRIKA_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> PEPPER_SEEDS = ModTabs.addToFoodTab(ITEMS.register("pepper_seeds", () -> new ItemNameBlockItem(ModBlocks.PEPPER_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> PINEAPPLE_SEEDS = ModTabs.addToFoodTab(ITEMS.register("pineapple_seeds", () -> new ItemNameBlockItem(ModBlocks.PINEAPPLE_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> TOMATO_SEEDS = ModTabs.addToFoodTab(ITEMS.register("tomato_seeds", () -> new ItemNameBlockItem(ModBlocks.TOMATO_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> STRAWBERRY_SEEDS = ModTabs.addToFoodTab(ITEMS.register("strawberry_seeds", () -> new ItemNameBlockItem(ModBlocks.STRAWBERRY_CROP.get(), new Item.Properties())));
    public static final RegistryObject<Item> WEED_SEEDS = ModTabs.addToFoodTab(ITEMS.register("weed_seeds", () -> new ItemNameBlockItem(ModBlocks.WEED_CROP.get(), new Item.Properties())));

//TOOLS
    public static final RegistryObject<Item> BLUE_CRYSTAL_SWORD = ModTabs.addToToolsTab(ITEMS.register("blue_crystal_sword", () -> new SwordItem(ModToolTiers.BLUE_CRYSTAL, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> BLUE_CRYSTAL_AXE = ModTabs.addToToolsTab(ITEMS.register("blue_crystal_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> BLUE_CRYSTAL_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("blue_crystal_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 2, new Item.Properties())));
    public static final RegistryObject<Item> BLUE_CRYSTAL_HOE = ModTabs.addToToolsTab(ITEMS.register("blue_crystal_hoe", () -> new HoeItem(ModToolTiers.BLUE_CRYSTAL, 0, 2, new Item.Properties())));
    public static final RegistryObject<Item> BLUE_CRYSTAL_SHOVEL = ModTabs.addToToolsTab(ITEMS.register("blue_crystal_shovel", () -> new ShovelItem(ModToolTiers.BLUE_CRYSTAL, 0, 2, new Item.Properties())));
    public static final RegistryObject<Item> SWORD_BLUE = ModTabs.addToToolsTab(ITEMS.register("sword_blue", () -> new SwordItem(ModToolTiers.BLUE_CRYSTAL, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> SWORD_GREEN = ModTabs.addToToolsTab(ITEMS.register("sword_green", () -> new SwordItem(ModToolTiers.BLUE_CRYSTAL, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> SWORD_GOLD = ModTabs.addToToolsTab(ITEMS.register("sword_gold", () -> new SwordItem(ModToolTiers.BLUE_CRYSTAL, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> SWORD_PINK = ModTabs.addToToolsTab(ITEMS.register("sword_pink", () -> new SwordItem(ModToolTiers.BLUE_CRYSTAL, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> CHRISTMAS_AXE = ModTabs.addToToolsTab(ITEMS.register("christmas_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> COPPER_AXE = ModTabs.addToToolsTab(ITEMS.register("copper_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> EMERALD_AXE = ModTabs.addToToolsTab(ITEMS.register("emerald_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> LAPIS_AXE = ModTabs.addToToolsTab(ITEMS.register("lapis_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> MAGMA_AXE = ModTabs.addToToolsTab(ITEMS.register("magma_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> OBSIDIAN_AXE = ModTabs.addToToolsTab(ITEMS.register("obsidian_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> REDSTONE_AXE = ModTabs.addToToolsTab(ITEMS.register("redstone_axe", () -> new AxeItem(ModToolTiers.BLUE_CRYSTAL, 6, 2, new Item.Properties())));
    public static final RegistryObject<Item> CLASSIC_KNIFE = ModTabs.addToToolsTab(ITEMS.register("classic_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> WHITE_KNIFE = ModTabs.addToToolsTab(ITEMS.register("white_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> RED_KNIFE = ModTabs.addToToolsTab(ITEMS.register("red_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> PINK_KNIFE = ModTabs.addToToolsTab(ITEMS.register("pink_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_KNIFE = ModTabs.addToToolsTab(ITEMS.register("purple_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> RAINBOW_KNIFE = ModTabs.addToToolsTab(ITEMS.register("rainbow_knife", () -> new SwordItem(ModToolTiers.MES, 4, 2, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK = ModTabs.addToToolsTab(ITEMS.register("wapenstok", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK_DIAMOND = ModTabs.addToToolsTab(ITEMS.register("wapenstok_diamond", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK_GOLD = ModTabs.addToToolsTab(ITEMS.register("wapenstok_gold", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK_EMERALD = ModTabs.addToToolsTab(ITEMS.register("wapenstok_emerald", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK_IRON = ModTabs.addToToolsTab(ITEMS.register("wapenstok_iron", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> WAPENSTOK_REDSTONE = ModTabs.addToToolsTab(ITEMS.register("wapenstok_redstone", () -> new SwordItem(ModToolTiers.WAPENSTOK, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> TASER = ModTabs.addToToolsTab(ITEMS.register("taser", () -> new SwordItem(ModToolTiers.TASER, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT = ModTabs.addToToolsTab(ITEMS.register("bat", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_DIAMOND = ModTabs.addToToolsTab(ITEMS.register("bat_diamond", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_GOLD = ModTabs.addToToolsTab(ITEMS.register("bat_gold", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_EMERALD = ModTabs.addToToolsTab(ITEMS.register("bat_emerald", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_IRON = ModTabs.addToToolsTab(ITEMS.register("bat_iron", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_REDSTONE = ModTabs.addToToolsTab(ITEMS.register("bat_redstone", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> BAT_GRAY = ModTabs.addToToolsTab(ITEMS.register("bat_gray", () -> new SwordItem(ModToolTiers.BAT, 0, 10, new Item.Properties())));
    public static final RegistryObject<Item> LIGHTSABER_BLUE = ModTabs.addToToolsTab(ITEMS.register("lightsaber_blue", () -> new SwordItem(ModToolTiers.LIGHTSABER, 1, 10, new Item.Properties())));
    public static final RegistryObject<Item> LIGHTSABER_GREEN = ModTabs.addToToolsTab(ITEMS.register("lightsaber_green", () -> new SwordItem(ModToolTiers.LIGHTSABER, 1, 10, new Item.Properties())));
    public static final RegistryObject<Item> LIGHTSABER_PURPLE = ModTabs.addToToolsTab(ITEMS.register("lightsaber_purple", () -> new SwordItem(ModToolTiers.LIGHTSABER, 1, 10, new Item.Properties())));
    public static final RegistryObject<Item> LIGHTSABER_RED = ModTabs.addToToolsTab(ITEMS.register("lightsaber_red", () -> new SwordItem(ModToolTiers.LIGHTSABER, 1, 10, new Item.Properties())));
    public static final RegistryObject<Item> LIGHTSABER_YELLOW = ModTabs.addToToolsTab(ITEMS.register("lightsaber_yellow", () -> new SwordItem(ModToolTiers.LIGHTSABER, 1, 10, new Item.Properties())));
    public static final RegistryObject<Item> SCYTHE = ModTabs.addToToolsTab(ITEMS.register("scythe", () -> new SwordItem(ModToolTiers.SCYTHE, 4, 3, new Item.Properties())));
    public static final RegistryObject<Item> CACTUS_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("cactus_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> COPPER_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("copper_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> DARK_PRISMARINE_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("dark_prismarine_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> LAVA_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("lava_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> MONDRIAAN_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("mondriaan_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> MORGANITE_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("morganite_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> NETHERPORTAL_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("netherportal_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> RUBY_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("ruby_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> SAPPHIRE_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("sapphire_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> SILVER_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("silver_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> WATER_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("water_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> MAGMA_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("magma_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> OBSIDIAN_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("obsidian_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));
    public static final RegistryObject<Item> EMERALD_PICKAXE = ModTabs.addToToolsTab(ITEMS.register("emerald_pickaxe", () -> new PickaxeItem(ModToolTiers.BLUE_CRYSTAL, 0, 1, new Item.Properties())));


public static void register(IEventBus eventbus) {
    ITEMS.register(eventbus);
    }
}
